### ISSUE TITLE
🐞 [BUG] - <Roadmap link for Game Development is not correct >

### ISSUE THREAD

**Issue by SaraNahata** [jfmartinz/ResourceHub#1256]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

Upon clicking the roadmap link for Game Development, the roadmap.sh site opens but shows "page not found". Hence, the link needs to be added correctly.
