### ISSUE TITLE
🐞 [BUG] - <fix roadmap links in UI/UX>

### ISSUE THREAD

**Issue by AmruthaPariprolu** [jfmartinz/ResourceHub#1509]
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

Fixing  tags  in UI/UX roadmap
